package com.qiguliuxing.dts.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class TbmState {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.time
     *
     * @mbg.generated
     */
    private LocalDateTime time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.tunnel_time
     *
     * @mbg.generated
     */
    private Integer tunnelTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.tunnel_mileage
     *
     * @mbg.generated
     */
    private Integer tunnelMileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.current_ring_num
     *
     * @mbg.generated
     */
    private Integer currentRingNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.tunnel_state
     *
     * @mbg.generated
     */
    private String tunnelState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.cutter_speed
     *
     * @mbg.generated
     */
    private BigDecimal cutterSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.tunnel_speed
     *
     * @mbg.generated
     */
    private BigDecimal tunnelSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.screw_speed
     *
     * @mbg.generated
     */
    private BigDecimal screwSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.left_right_pressure
     *
     * @mbg.generated
     */
    private BigDecimal leftRightPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.up_down_pressure
     *
     * @mbg.generated
     */
    private BigDecimal upDownPressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.current_horattitude_before
     *
     * @mbg.generated
     */
    private BigDecimal currentHorattitudeBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.current_horattitude_after
     *
     * @mbg.generated
     */
    private BigDecimal currentHorattitudeAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.current_verattitude_before
     *
     * @mbg.generated
     */
    private BigDecimal currentVerattitudeBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.current_verattitude_after
     *
     * @mbg.generated
     */
    private BigDecimal currentVerattitudeAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.next_horattitude_before
     *
     * @mbg.generated
     */
    private BigDecimal nextHorattitudeBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.next_horattitude_after
     *
     * @mbg.generated
     */
    private BigDecimal nextHorattitudeAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.next_verattitude_before
     *
     * @mbg.generated
     */
    private BigDecimal nextVerattitudeBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbm_state.next_verattitude_after
     *
     * @mbg.generated
     */
    private BigDecimal nextVerattitudeAfter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.id
     *
     * @return the value of tbm_state.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.id
     *
     * @param id the value for tbm_state.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.time
     *
     * @return the value of tbm_state.time
     *
     * @mbg.generated
     */
    public LocalDateTime getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.time
     *
     * @param time the value for tbm_state.time
     *
     * @mbg.generated
     */
    public void setTime(LocalDateTime time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.tunnel_time
     *
     * @return the value of tbm_state.tunnel_time
     *
     * @mbg.generated
     */
    public Integer getTunnelTime() {
        return tunnelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.tunnel_time
     *
     * @param tunnelTime the value for tbm_state.tunnel_time
     *
     * @mbg.generated
     */
    public void setTunnelTime(Integer tunnelTime) {
        this.tunnelTime = tunnelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.tunnel_mileage
     *
     * @return the value of tbm_state.tunnel_mileage
     *
     * @mbg.generated
     */
    public Integer getTunnelMileage() {
        return tunnelMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.tunnel_mileage
     *
     * @param tunnelMileage the value for tbm_state.tunnel_mileage
     *
     * @mbg.generated
     */
    public void setTunnelMileage(Integer tunnelMileage) {
        this.tunnelMileage = tunnelMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.current_ring_num
     *
     * @return the value of tbm_state.current_ring_num
     *
     * @mbg.generated
     */
    public Integer getCurrentRingNum() {
        return currentRingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.current_ring_num
     *
     * @param currentRingNum the value for tbm_state.current_ring_num
     *
     * @mbg.generated
     */
    public void setCurrentRingNum(Integer currentRingNum) {
        this.currentRingNum = currentRingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.tunnel_state
     *
     * @return the value of tbm_state.tunnel_state
     *
     * @mbg.generated
     */
    public String getTunnelState() {
        return tunnelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.tunnel_state
     *
     * @param tunnelState the value for tbm_state.tunnel_state
     *
     * @mbg.generated
     */
    public void setTunnelState(String tunnelState) {
        this.tunnelState = tunnelState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.cutter_speed
     *
     * @return the value of tbm_state.cutter_speed
     *
     * @mbg.generated
     */
    public BigDecimal getCutterSpeed() {
        return cutterSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.cutter_speed
     *
     * @param cutterSpeed the value for tbm_state.cutter_speed
     *
     * @mbg.generated
     */
    public void setCutterSpeed(BigDecimal cutterSpeed) {
        this.cutterSpeed = cutterSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.tunnel_speed
     *
     * @return the value of tbm_state.tunnel_speed
     *
     * @mbg.generated
     */
    public BigDecimal getTunnelSpeed() {
        return tunnelSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.tunnel_speed
     *
     * @param tunnelSpeed the value for tbm_state.tunnel_speed
     *
     * @mbg.generated
     */
    public void setTunnelSpeed(BigDecimal tunnelSpeed) {
        this.tunnelSpeed = tunnelSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.screw_speed
     *
     * @return the value of tbm_state.screw_speed
     *
     * @mbg.generated
     */
    public BigDecimal getScrewSpeed() {
        return screwSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.screw_speed
     *
     * @param screwSpeed the value for tbm_state.screw_speed
     *
     * @mbg.generated
     */
    public void setScrewSpeed(BigDecimal screwSpeed) {
        this.screwSpeed = screwSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.left_right_pressure
     *
     * @return the value of tbm_state.left_right_pressure
     *
     * @mbg.generated
     */
    public BigDecimal getLeftRightPressure() {
        return leftRightPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.left_right_pressure
     *
     * @param leftRightPressure the value for tbm_state.left_right_pressure
     *
     * @mbg.generated
     */
    public void setLeftRightPressure(BigDecimal leftRightPressure) {
        this.leftRightPressure = leftRightPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.up_down_pressure
     *
     * @return the value of tbm_state.up_down_pressure
     *
     * @mbg.generated
     */
    public BigDecimal getUpDownPressure() {
        return upDownPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.up_down_pressure
     *
     * @param upDownPressure the value for tbm_state.up_down_pressure
     *
     * @mbg.generated
     */
    public void setUpDownPressure(BigDecimal upDownPressure) {
        this.upDownPressure = upDownPressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.current_horattitude_before
     *
     * @return the value of tbm_state.current_horattitude_before
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentHorattitudeBefore() {
        return currentHorattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.current_horattitude_before
     *
     * @param currentHorattitudeBefore the value for tbm_state.current_horattitude_before
     *
     * @mbg.generated
     */
    public void setCurrentHorattitudeBefore(BigDecimal currentHorattitudeBefore) {
        this.currentHorattitudeBefore = currentHorattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.current_horattitude_after
     *
     * @return the value of tbm_state.current_horattitude_after
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentHorattitudeAfter() {
        return currentHorattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.current_horattitude_after
     *
     * @param currentHorattitudeAfter the value for tbm_state.current_horattitude_after
     *
     * @mbg.generated
     */
    public void setCurrentHorattitudeAfter(BigDecimal currentHorattitudeAfter) {
        this.currentHorattitudeAfter = currentHorattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.current_verattitude_before
     *
     * @return the value of tbm_state.current_verattitude_before
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentVerattitudeBefore() {
        return currentVerattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.current_verattitude_before
     *
     * @param currentVerattitudeBefore the value for tbm_state.current_verattitude_before
     *
     * @mbg.generated
     */
    public void setCurrentVerattitudeBefore(BigDecimal currentVerattitudeBefore) {
        this.currentVerattitudeBefore = currentVerattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.current_verattitude_after
     *
     * @return the value of tbm_state.current_verattitude_after
     *
     * @mbg.generated
     */
    public BigDecimal getCurrentVerattitudeAfter() {
        return currentVerattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.current_verattitude_after
     *
     * @param currentVerattitudeAfter the value for tbm_state.current_verattitude_after
     *
     * @mbg.generated
     */
    public void setCurrentVerattitudeAfter(BigDecimal currentVerattitudeAfter) {
        this.currentVerattitudeAfter = currentVerattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.next_horattitude_before
     *
     * @return the value of tbm_state.next_horattitude_before
     *
     * @mbg.generated
     */
    public BigDecimal getNextHorattitudeBefore() {
        return nextHorattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.next_horattitude_before
     *
     * @param nextHorattitudeBefore the value for tbm_state.next_horattitude_before
     *
     * @mbg.generated
     */
    public void setNextHorattitudeBefore(BigDecimal nextHorattitudeBefore) {
        this.nextHorattitudeBefore = nextHorattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.next_horattitude_after
     *
     * @return the value of tbm_state.next_horattitude_after
     *
     * @mbg.generated
     */
    public BigDecimal getNextHorattitudeAfter() {
        return nextHorattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.next_horattitude_after
     *
     * @param nextHorattitudeAfter the value for tbm_state.next_horattitude_after
     *
     * @mbg.generated
     */
    public void setNextHorattitudeAfter(BigDecimal nextHorattitudeAfter) {
        this.nextHorattitudeAfter = nextHorattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.next_verattitude_before
     *
     * @return the value of tbm_state.next_verattitude_before
     *
     * @mbg.generated
     */
    public BigDecimal getNextVerattitudeBefore() {
        return nextVerattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.next_verattitude_before
     *
     * @param nextVerattitudeBefore the value for tbm_state.next_verattitude_before
     *
     * @mbg.generated
     */
    public void setNextVerattitudeBefore(BigDecimal nextVerattitudeBefore) {
        this.nextVerattitudeBefore = nextVerattitudeBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbm_state.next_verattitude_after
     *
     * @return the value of tbm_state.next_verattitude_after
     *
     * @mbg.generated
     */
    public BigDecimal getNextVerattitudeAfter() {
        return nextVerattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbm_state.next_verattitude_after
     *
     * @param nextVerattitudeAfter the value for tbm_state.next_verattitude_after
     *
     * @mbg.generated
     */
    public void setNextVerattitudeAfter(BigDecimal nextVerattitudeAfter) {
        this.nextVerattitudeAfter = nextVerattitudeAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", time=").append(time);
        sb.append(", tunnelTime=").append(tunnelTime);
        sb.append(", tunnelMileage=").append(tunnelMileage);
        sb.append(", currentRingNum=").append(currentRingNum);
        sb.append(", tunnelState=").append(tunnelState);
        sb.append(", cutterSpeed=").append(cutterSpeed);
        sb.append(", tunnelSpeed=").append(tunnelSpeed);
        sb.append(", screwSpeed=").append(screwSpeed);
        sb.append(", leftRightPressure=").append(leftRightPressure);
        sb.append(", upDownPressure=").append(upDownPressure);
        sb.append(", currentHorattitudeBefore=").append(currentHorattitudeBefore);
        sb.append(", currentHorattitudeAfter=").append(currentHorattitudeAfter);
        sb.append(", currentVerattitudeBefore=").append(currentVerattitudeBefore);
        sb.append(", currentVerattitudeAfter=").append(currentVerattitudeAfter);
        sb.append(", nextHorattitudeBefore=").append(nextHorattitudeBefore);
        sb.append(", nextHorattitudeAfter=").append(nextHorattitudeAfter);
        sb.append(", nextVerattitudeBefore=").append(nextVerattitudeBefore);
        sb.append(", nextVerattitudeAfter=").append(nextVerattitudeAfter);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TbmState other = (TbmState) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getTunnelTime() == null ? other.getTunnelTime() == null : this.getTunnelTime().equals(other.getTunnelTime()))
            && (this.getTunnelMileage() == null ? other.getTunnelMileage() == null : this.getTunnelMileage().equals(other.getTunnelMileage()))
            && (this.getCurrentRingNum() == null ? other.getCurrentRingNum() == null : this.getCurrentRingNum().equals(other.getCurrentRingNum()))
            && (this.getTunnelState() == null ? other.getTunnelState() == null : this.getTunnelState().equals(other.getTunnelState()))
            && (this.getCutterSpeed() == null ? other.getCutterSpeed() == null : this.getCutterSpeed().equals(other.getCutterSpeed()))
            && (this.getTunnelSpeed() == null ? other.getTunnelSpeed() == null : this.getTunnelSpeed().equals(other.getTunnelSpeed()))
            && (this.getScrewSpeed() == null ? other.getScrewSpeed() == null : this.getScrewSpeed().equals(other.getScrewSpeed()))
            && (this.getLeftRightPressure() == null ? other.getLeftRightPressure() == null : this.getLeftRightPressure().equals(other.getLeftRightPressure()))
            && (this.getUpDownPressure() == null ? other.getUpDownPressure() == null : this.getUpDownPressure().equals(other.getUpDownPressure()))
            && (this.getCurrentHorattitudeBefore() == null ? other.getCurrentHorattitudeBefore() == null : this.getCurrentHorattitudeBefore().equals(other.getCurrentHorattitudeBefore()))
            && (this.getCurrentHorattitudeAfter() == null ? other.getCurrentHorattitudeAfter() == null : this.getCurrentHorattitudeAfter().equals(other.getCurrentHorattitudeAfter()))
            && (this.getCurrentVerattitudeBefore() == null ? other.getCurrentVerattitudeBefore() == null : this.getCurrentVerattitudeBefore().equals(other.getCurrentVerattitudeBefore()))
            && (this.getCurrentVerattitudeAfter() == null ? other.getCurrentVerattitudeAfter() == null : this.getCurrentVerattitudeAfter().equals(other.getCurrentVerattitudeAfter()))
            && (this.getNextHorattitudeBefore() == null ? other.getNextHorattitudeBefore() == null : this.getNextHorattitudeBefore().equals(other.getNextHorattitudeBefore()))
            && (this.getNextHorattitudeAfter() == null ? other.getNextHorattitudeAfter() == null : this.getNextHorattitudeAfter().equals(other.getNextHorattitudeAfter()))
            && (this.getNextVerattitudeBefore() == null ? other.getNextVerattitudeBefore() == null : this.getNextVerattitudeBefore().equals(other.getNextVerattitudeBefore()))
            && (this.getNextVerattitudeAfter() == null ? other.getNextVerattitudeAfter() == null : this.getNextVerattitudeAfter().equals(other.getNextVerattitudeAfter()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getTunnelTime() == null) ? 0 : getTunnelTime().hashCode());
        result = prime * result + ((getTunnelMileage() == null) ? 0 : getTunnelMileage().hashCode());
        result = prime * result + ((getCurrentRingNum() == null) ? 0 : getCurrentRingNum().hashCode());
        result = prime * result + ((getTunnelState() == null) ? 0 : getTunnelState().hashCode());
        result = prime * result + ((getCutterSpeed() == null) ? 0 : getCutterSpeed().hashCode());
        result = prime * result + ((getTunnelSpeed() == null) ? 0 : getTunnelSpeed().hashCode());
        result = prime * result + ((getScrewSpeed() == null) ? 0 : getScrewSpeed().hashCode());
        result = prime * result + ((getLeftRightPressure() == null) ? 0 : getLeftRightPressure().hashCode());
        result = prime * result + ((getUpDownPressure() == null) ? 0 : getUpDownPressure().hashCode());
        result = prime * result + ((getCurrentHorattitudeBefore() == null) ? 0 : getCurrentHorattitudeBefore().hashCode());
        result = prime * result + ((getCurrentHorattitudeAfter() == null) ? 0 : getCurrentHorattitudeAfter().hashCode());
        result = prime * result + ((getCurrentVerattitudeBefore() == null) ? 0 : getCurrentVerattitudeBefore().hashCode());
        result = prime * result + ((getCurrentVerattitudeAfter() == null) ? 0 : getCurrentVerattitudeAfter().hashCode());
        result = prime * result + ((getNextHorattitudeBefore() == null) ? 0 : getNextHorattitudeBefore().hashCode());
        result = prime * result + ((getNextHorattitudeAfter() == null) ? 0 : getNextHorattitudeAfter().hashCode());
        result = prime * result + ((getNextVerattitudeBefore() == null) ? 0 : getNextVerattitudeBefore().hashCode());
        result = prime * result + ((getNextVerattitudeAfter() == null) ? 0 : getNextVerattitudeAfter().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        time("time"),
        tunnelTime("tunnel_time"),
        tunnelMileage("tunnel_mileage"),
        currentRingNum("current_ring_num"),
        tunnelState("tunnel_state"),
        cutterSpeed("cutter_speed"),
        tunnelSpeed("tunnel_speed"),
        screwSpeed("screw_speed"),
        leftRightPressure("left_right_pressure"),
        upDownPressure("up_down_pressure"),
        currentHorattitudeBefore("current_horattitude_before"),
        currentHorattitudeAfter("current_horattitude_after"),
        currentVerattitudeBefore("current_verattitude_before"),
        currentVerattitudeAfter("current_verattitude_after"),
        nextHorattitudeBefore("next_horattitude_before"),
        nextHorattitudeAfter("next_horattitude_after"),
        nextVerattitudeBefore("next_verattitude_before"),
        nextVerattitudeAfter("next_verattitude_after");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}