package com.qiguliuxing.dts.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TbmStateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public TbmStateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public TbmStateExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public TbmStateExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("`time` is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("`time` is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(LocalDateTime value) {
            addCriterion("`time` =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`time` <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(LocalDateTime value) {
            addCriterion("`time` >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`time` >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(LocalDateTime value) {
            addCriterion("`time` <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`time` <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<LocalDateTime> values) {
            addCriterion("`time` in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`time` not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`time` between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`time` not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeIsNull() {
            addCriterion("tunnel_time is null");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeIsNotNull() {
            addCriterion("tunnel_time is not null");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeEqualTo(Integer value) {
            addCriterion("tunnel_time =", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeNotEqualTo(Integer value) {
            addCriterion("tunnel_time <>", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeGreaterThan(Integer value) {
            addCriterion("tunnel_time >", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tunnel_time >=", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeLessThan(Integer value) {
            addCriterion("tunnel_time <", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeLessThanOrEqualTo(Integer value) {
            addCriterion("tunnel_time <=", value, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeIn(List<Integer> values) {
            addCriterion("tunnel_time in", values, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeNotIn(List<Integer> values) {
            addCriterion("tunnel_time not in", values, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeBetween(Integer value1, Integer value2) {
            addCriterion("tunnel_time between", value1, value2, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("tunnel_time not between", value1, value2, "tunnelTime");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageIsNull() {
            addCriterion("tunnel_mileage is null");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageIsNotNull() {
            addCriterion("tunnel_mileage is not null");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageEqualTo(Integer value) {
            addCriterion("tunnel_mileage =", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageNotEqualTo(Integer value) {
            addCriterion("tunnel_mileage <>", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageGreaterThan(Integer value) {
            addCriterion("tunnel_mileage >", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageGreaterThanOrEqualTo(Integer value) {
            addCriterion("tunnel_mileage >=", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageLessThan(Integer value) {
            addCriterion("tunnel_mileage <", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageLessThanOrEqualTo(Integer value) {
            addCriterion("tunnel_mileage <=", value, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageIn(List<Integer> values) {
            addCriterion("tunnel_mileage in", values, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageNotIn(List<Integer> values) {
            addCriterion("tunnel_mileage not in", values, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageBetween(Integer value1, Integer value2) {
            addCriterion("tunnel_mileage between", value1, value2, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andTunnelMileageNotBetween(Integer value1, Integer value2) {
            addCriterion("tunnel_mileage not between", value1, value2, "tunnelMileage");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumIsNull() {
            addCriterion("current_ring_num is null");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumIsNotNull() {
            addCriterion("current_ring_num is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumEqualTo(Integer value) {
            addCriterion("current_ring_num =", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumNotEqualTo(Integer value) {
            addCriterion("current_ring_num <>", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumGreaterThan(Integer value) {
            addCriterion("current_ring_num >", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("current_ring_num >=", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumLessThan(Integer value) {
            addCriterion("current_ring_num <", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumLessThanOrEqualTo(Integer value) {
            addCriterion("current_ring_num <=", value, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumIn(List<Integer> values) {
            addCriterion("current_ring_num in", values, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumNotIn(List<Integer> values) {
            addCriterion("current_ring_num not in", values, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumBetween(Integer value1, Integer value2) {
            addCriterion("current_ring_num between", value1, value2, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andCurrentRingNumNotBetween(Integer value1, Integer value2) {
            addCriterion("current_ring_num not between", value1, value2, "currentRingNum");
            return (Criteria) this;
        }

        public Criteria andTunnelStateIsNull() {
            addCriterion("tunnel_state is null");
            return (Criteria) this;
        }

        public Criteria andTunnelStateIsNotNull() {
            addCriterion("tunnel_state is not null");
            return (Criteria) this;
        }

        public Criteria andTunnelStateEqualTo(String value) {
            addCriterion("tunnel_state =", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateNotEqualTo(String value) {
            addCriterion("tunnel_state <>", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateGreaterThan(String value) {
            addCriterion("tunnel_state >", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateGreaterThanOrEqualTo(String value) {
            addCriterion("tunnel_state >=", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateLessThan(String value) {
            addCriterion("tunnel_state <", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateLessThanOrEqualTo(String value) {
            addCriterion("tunnel_state <=", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateLike(String value) {
            addCriterion("tunnel_state like", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateNotLike(String value) {
            addCriterion("tunnel_state not like", value, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateIn(List<String> values) {
            addCriterion("tunnel_state in", values, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateNotIn(List<String> values) {
            addCriterion("tunnel_state not in", values, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateBetween(String value1, String value2) {
            addCriterion("tunnel_state between", value1, value2, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andTunnelStateNotBetween(String value1, String value2) {
            addCriterion("tunnel_state not between", value1, value2, "tunnelState");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedIsNull() {
            addCriterion("cutter_speed is null");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedIsNotNull() {
            addCriterion("cutter_speed is not null");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedEqualTo(BigDecimal value) {
            addCriterion("cutter_speed =", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedNotEqualTo(BigDecimal value) {
            addCriterion("cutter_speed <>", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedGreaterThan(BigDecimal value) {
            addCriterion("cutter_speed >", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cutter_speed >=", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedLessThan(BigDecimal value) {
            addCriterion("cutter_speed <", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cutter_speed <=", value, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedIn(List<BigDecimal> values) {
            addCriterion("cutter_speed in", values, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedNotIn(List<BigDecimal> values) {
            addCriterion("cutter_speed not in", values, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cutter_speed between", value1, value2, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andCutterSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cutter_speed not between", value1, value2, "cutterSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedIsNull() {
            addCriterion("tunnel_speed is null");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedIsNotNull() {
            addCriterion("tunnel_speed is not null");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedEqualTo(BigDecimal value) {
            addCriterion("tunnel_speed =", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedNotEqualTo(BigDecimal value) {
            addCriterion("tunnel_speed <>", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedGreaterThan(BigDecimal value) {
            addCriterion("tunnel_speed >", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tunnel_speed >=", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedLessThan(BigDecimal value) {
            addCriterion("tunnel_speed <", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tunnel_speed <=", value, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedIn(List<BigDecimal> values) {
            addCriterion("tunnel_speed in", values, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedNotIn(List<BigDecimal> values) {
            addCriterion("tunnel_speed not in", values, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tunnel_speed between", value1, value2, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andTunnelSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tunnel_speed not between", value1, value2, "tunnelSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedIsNull() {
            addCriterion("screw_speed is null");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedIsNotNull() {
            addCriterion("screw_speed is not null");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedEqualTo(BigDecimal value) {
            addCriterion("screw_speed =", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedNotEqualTo(BigDecimal value) {
            addCriterion("screw_speed <>", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedGreaterThan(BigDecimal value) {
            addCriterion("screw_speed >", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("screw_speed >=", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedLessThan(BigDecimal value) {
            addCriterion("screw_speed <", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("screw_speed <=", value, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedIn(List<BigDecimal> values) {
            addCriterion("screw_speed in", values, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedNotIn(List<BigDecimal> values) {
            addCriterion("screw_speed not in", values, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("screw_speed between", value1, value2, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andScrewSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("screw_speed not between", value1, value2, "screwSpeed");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureIsNull() {
            addCriterion("left_right_pressure is null");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureIsNotNull() {
            addCriterion("left_right_pressure is not null");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureEqualTo(BigDecimal value) {
            addCriterion("left_right_pressure =", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureNotEqualTo(BigDecimal value) {
            addCriterion("left_right_pressure <>", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureGreaterThan(BigDecimal value) {
            addCriterion("left_right_pressure >", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("left_right_pressure >=", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureLessThan(BigDecimal value) {
            addCriterion("left_right_pressure <", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("left_right_pressure <=", value, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureIn(List<BigDecimal> values) {
            addCriterion("left_right_pressure in", values, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureNotIn(List<BigDecimal> values) {
            addCriterion("left_right_pressure not in", values, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_right_pressure between", value1, value2, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andLeftRightPressureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("left_right_pressure not between", value1, value2, "leftRightPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureIsNull() {
            addCriterion("up_down_pressure is null");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureIsNotNull() {
            addCriterion("up_down_pressure is not null");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureEqualTo(BigDecimal value) {
            addCriterion("up_down_pressure =", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureNotEqualTo(BigDecimal value) {
            addCriterion("up_down_pressure <>", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureGreaterThan(BigDecimal value) {
            addCriterion("up_down_pressure >", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("up_down_pressure >=", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureLessThan(BigDecimal value) {
            addCriterion("up_down_pressure <", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureLessThanOrEqualTo(BigDecimal value) {
            addCriterion("up_down_pressure <=", value, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureIn(List<BigDecimal> values) {
            addCriterion("up_down_pressure in", values, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureNotIn(List<BigDecimal> values) {
            addCriterion("up_down_pressure not in", values, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("up_down_pressure between", value1, value2, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andUpDownPressureNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("up_down_pressure not between", value1, value2, "upDownPressure");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeIsNull() {
            addCriterion("current_horattitude_before is null");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeIsNotNull() {
            addCriterion("current_horattitude_before is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_before =", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeNotEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_before <>", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeGreaterThan(BigDecimal value) {
            addCriterion("current_horattitude_before >", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_before >=", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeLessThan(BigDecimal value) {
            addCriterion("current_horattitude_before <", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_before <=", value, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeIn(List<BigDecimal> values) {
            addCriterion("current_horattitude_before in", values, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeNotIn(List<BigDecimal> values) {
            addCriterion("current_horattitude_before not in", values, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_horattitude_before between", value1, value2, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_horattitude_before not between", value1, value2, "currentHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterIsNull() {
            addCriterion("current_horattitude_after is null");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterIsNotNull() {
            addCriterion("current_horattitude_after is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_after =", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterNotEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_after <>", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterGreaterThan(BigDecimal value) {
            addCriterion("current_horattitude_after >", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_after >=", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterLessThan(BigDecimal value) {
            addCriterion("current_horattitude_after <", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_horattitude_after <=", value, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterIn(List<BigDecimal> values) {
            addCriterion("current_horattitude_after in", values, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterNotIn(List<BigDecimal> values) {
            addCriterion("current_horattitude_after not in", values, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_horattitude_after between", value1, value2, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentHorattitudeAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_horattitude_after not between", value1, value2, "currentHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeIsNull() {
            addCriterion("current_verattitude_before is null");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeIsNotNull() {
            addCriterion("current_verattitude_before is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_before =", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeNotEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_before <>", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeGreaterThan(BigDecimal value) {
            addCriterion("current_verattitude_before >", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_before >=", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeLessThan(BigDecimal value) {
            addCriterion("current_verattitude_before <", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_before <=", value, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeIn(List<BigDecimal> values) {
            addCriterion("current_verattitude_before in", values, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeNotIn(List<BigDecimal> values) {
            addCriterion("current_verattitude_before not in", values, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_verattitude_before between", value1, value2, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_verattitude_before not between", value1, value2, "currentVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterIsNull() {
            addCriterion("current_verattitude_after is null");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterIsNotNull() {
            addCriterion("current_verattitude_after is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_after =", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterNotEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_after <>", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterGreaterThan(BigDecimal value) {
            addCriterion("current_verattitude_after >", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_after >=", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterLessThan(BigDecimal value) {
            addCriterion("current_verattitude_after <", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_verattitude_after <=", value, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterIn(List<BigDecimal> values) {
            addCriterion("current_verattitude_after in", values, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterNotIn(List<BigDecimal> values) {
            addCriterion("current_verattitude_after not in", values, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_verattitude_after between", value1, value2, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andCurrentVerattitudeAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_verattitude_after not between", value1, value2, "currentVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeIsNull() {
            addCriterion("next_horattitude_before is null");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeIsNotNull() {
            addCriterion("next_horattitude_before is not null");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_before =", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeNotEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_before <>", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeGreaterThan(BigDecimal value) {
            addCriterion("next_horattitude_before >", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_before >=", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeLessThan(BigDecimal value) {
            addCriterion("next_horattitude_before <", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_before <=", value, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeIn(List<BigDecimal> values) {
            addCriterion("next_horattitude_before in", values, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeNotIn(List<BigDecimal> values) {
            addCriterion("next_horattitude_before not in", values, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_horattitude_before between", value1, value2, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_horattitude_before not between", value1, value2, "nextHorattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterIsNull() {
            addCriterion("next_horattitude_after is null");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterIsNotNull() {
            addCriterion("next_horattitude_after is not null");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_after =", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterNotEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_after <>", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterGreaterThan(BigDecimal value) {
            addCriterion("next_horattitude_after >", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_after >=", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterLessThan(BigDecimal value) {
            addCriterion("next_horattitude_after <", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("next_horattitude_after <=", value, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterIn(List<BigDecimal> values) {
            addCriterion("next_horattitude_after in", values, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterNotIn(List<BigDecimal> values) {
            addCriterion("next_horattitude_after not in", values, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_horattitude_after between", value1, value2, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextHorattitudeAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_horattitude_after not between", value1, value2, "nextHorattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeIsNull() {
            addCriterion("next_verattitude_before is null");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeIsNotNull() {
            addCriterion("next_verattitude_before is not null");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_before =", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeNotEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_before <>", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeGreaterThan(BigDecimal value) {
            addCriterion("next_verattitude_before >", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_before >=", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeLessThan(BigDecimal value) {
            addCriterion("next_verattitude_before <", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_before <=", value, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeIn(List<BigDecimal> values) {
            addCriterion("next_verattitude_before in", values, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeNotIn(List<BigDecimal> values) {
            addCriterion("next_verattitude_before not in", values, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_verattitude_before between", value1, value2, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeBeforeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_verattitude_before not between", value1, value2, "nextVerattitudeBefore");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterIsNull() {
            addCriterion("next_verattitude_after is null");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterIsNotNull() {
            addCriterion("next_verattitude_after is not null");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_after =", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterNotEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_after <>", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterGreaterThan(BigDecimal value) {
            addCriterion("next_verattitude_after >", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_after >=", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterLessThan(BigDecimal value) {
            addCriterion("next_verattitude_after <", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterLessThanOrEqualTo(BigDecimal value) {
            addCriterion("next_verattitude_after <=", value, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterIn(List<BigDecimal> values) {
            addCriterion("next_verattitude_after in", values, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterNotIn(List<BigDecimal> values) {
            addCriterion("next_verattitude_after not in", values, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_verattitude_after between", value1, value2, "nextVerattitudeAfter");
            return (Criteria) this;
        }

        public Criteria andNextVerattitudeAfterNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("next_verattitude_after not between", value1, value2, "nextVerattitudeAfter");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbm_state
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private TbmStateExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(TbmStateExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public TbmStateExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table tbm_state
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table tbm_state
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}