package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.TbmAdmin;
import com.qiguliuxing.dts.db.domain.TbmAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbmAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    long countByExample(TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int deleteByExample(TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int insert(TbmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int insertSelective(TbmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmAdmin selectOneByExample(TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmAdmin selectOneByExampleSelective(@Param("example") TbmAdminExample example, @Param("selective") TbmAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbmAdmin> selectByExampleSelective(@Param("example") TbmAdminExample example, @Param("selective") TbmAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    List<TbmAdmin> selectByExample(TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbmAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    TbmAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbmAdmin record, @Param("example") TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbmAdmin record, @Param("example") TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbmAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TbmAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}