package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.TbmRegion;
import com.qiguliuxing.dts.db.domain.TbmRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbmRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    long countByExample(TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int deleteByExample(TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int insert(TbmRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int insertSelective(TbmRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRegion selectOneByExample(TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRegion selectOneByExampleSelective(@Param("example") TbmRegionExample example, @Param("selective") TbmRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbmRegion> selectByExampleSelective(@Param("example") TbmRegionExample example, @Param("selective") TbmRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    List<TbmRegion> selectByExample(TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRegion selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbmRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    TbmRegion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbmRegion record, @Param("example") TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbmRegion record, @Param("example") TbmRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbmRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbmRegion record);
}