package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.TbmRole;
import com.qiguliuxing.dts.db.domain.TbmRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    long countByExample(TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int deleteByExample(TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int insert(TbmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int insertSelective(TbmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRole selectOneByExample(TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRole selectOneByExampleSelective(@Param("example") TbmRoleExample example, @Param("selective") TbmRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbmRole> selectByExampleSelective(@Param("example") TbmRoleExample example, @Param("selective") TbmRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    List<TbmRole> selectByExample(TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbmRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    TbmRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbmRole record, @Param("example") TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbmRole record, @Param("example") TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") TbmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dts_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}