package com.qiguliuxing.dts.db.dao;

import com.qiguliuxing.dts.db.domain.TbmState;
import com.qiguliuxing.dts.db.domain.TbmStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbmStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    long countByExample(TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int deleteByExample(TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int insert(TbmState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int insertSelective(TbmState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    List<TbmState> selectByExample(TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<TbmState> selectByExampleSelective(@Param("example") TbmStateExample example, @Param("selective") TbmState.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    TbmState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmState selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TbmState.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TbmState record, @Param("example") TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TbmState record, @Param("example") TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TbmState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TbmState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmState selectOneByExample(TbmStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbm_state
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    TbmState selectOneByExampleSelective(@Param("example") TbmStateExample example, @Param("selective") TbmState.Column ... selective);
}